flyway.url=jdbc:mysql://mysql:3306/gigs?allowPublicKeyRetrieval=true&useSSL=false
flyway.user=root
flyway.password=rootpassword
flyway.locations=filesystem:/flyway/sql
flyway.baselineOnMigrate=true
flyway.validateMigrationNaming=true